#!/usr/bin/env -S python3 -u

import json
import struct
import sys
import urllib.parse
from pathlib import Path
from subprocess import Popen, run

# Read a message from stdin and decode it.


def get_message():
    raw_length = sys.stdin.buffer.read(4)

    if not raw_length:
        sys.exit(0)
    message_length = struct.unpack("=I", raw_length)[0]
    message = sys.stdin.buffer.read(message_length).decode("utf-8")
    return json.loads(message)

# Encode a message for transmission, given its content.


def encode_message(message_content):
    encoded_content = json.dumps(message_content).encode("utf-8")
    encoded_length = struct.pack("=I", len(encoded_content))
    return {
        "length": encoded_length,
        "content": struct.pack(str(len(encoded_content)) + "s", encoded_content),
    }

# Send an encoded message to stdout.


def send_message(encoded_message):
    sys.stdout.buffer.write(encoded_message["length"])
    sys.stdout.buffer.write(encoded_message["content"])
    sys.stdout.buffer.flush()


BASE_DIRECTORY = Path.home() / "misc" / "video"

message = get_message()

action = message["action"]
if action == "test":
    reply = {"success": True}
elif action == "download":
    url = message["url"]

    netloc = urllib.parse.urlparse(url).netloc
    if netloc.startswith("www."):
        netloc = netloc[4:]
    domain_name = netloc.split('.')[0]

    download_directory = BASE_DIRECTORY / domain_name
    download_directory.mkdir(parents=True, exist_ok=True)

    p = run(
        ["yt-dlp", "--print-json", "--", url],
        capture_output=True,
        text=True,
        cwd=download_directory,
    )
    if p.returncode == 0:
        output = json.loads(p.stdout)
        reply = {
            "success": True,
            "path": str(download_directory / output["_filename"]),
            "title": output["title"],
            "thumbnail": output["thumbnail"],
        }
    else:
        reply = {
            "success": False,
            "error": p.stderr,
        }
elif action == "open":
    path = message["path"]
    Popen(["xdg-open", path])
    reply = {"success": True}
elif action == "show":
    path = message["path"]
    Popen(["nautilus", "--", path])
    reply = {"success": True}
else:
    print(f"Got unknown action: {message}", file=sys.stderr)
    reply = {"success": False, "error": f"Unknown action: {action}"}

send_message(encode_message(reply))
